hagaki.pdf:hagaki.tex hagaki.insert.tex
	d:/tex/bin/platex.exe -kanji=utf8 hagaki.tex
	d:/tex/bin/dvipdfmx.exe -p "100mm,148mm" hagaki.dvi
	rm *.log *.aux *.dvi

Atena.pdf: Atena.tex
	d:/tex/bin/platex.exe -kanji=utf8 Atena.tex
	d:/tex/bin/dvipdfmx.exe -p a4 Atena.dvi
	rm *.log *.aux *.dvi
