name:                OpenPDF
version:             0.1.0.0
github:              "githubuser/OpenPDF"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/OpenPDF#readme>

default-extensions:
  - DataKinds
  - OverloadedLabels
  - TypeApplications
  - TypeOperators
  - OverloadedStrings

dependencies:
- base >= 4.7 && < 5
- Match
- process

library:
  source-dirs: src

executables:
  OpenPDF-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - OpenPDF

tests:
  OpenPDF-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - OpenPDF
