fileTree:
  "y:/労働保険事務組合/電子申請e-Gov"
  # "d:/test/"
directorySpec:
  - "事業所コード"
  - "事業所名"
  - "手続名"
  - "被保険者名"
  - "現在状況"
  - "社労士"
hihoSpec:
  - "事業所コード (1)"
  - "従業員コード (2)"
  - "事業所名 (3)"
  - "社員氏名 (4)"
  - "社員氏名カナ (5)"
  - "生年月日 (7)"
  - "郵便番号 (8)"
  - "住所1 (9)"
  - "住所2 (10)"
  - "電話番号 (12)"
  - "被保険者番号 (199)"
  - "取得年月日 (201)"
  - "喪失年月日 (207)"
  - "労災_労働保険番号 (249)"
  - "雇用_労働保険番号 (251)"
  - "外国人_国籍 (231)"
  # 2019/2/5 追加
  - "賃金月額 (204)"
  - "所定労働時間_時 (208)"
  - "所定労働時間_分 (209)"
  - "賃金支払の態様 (230)"
  - "外国人_国籍 (231)"
  - "外国人_在留資格 (232)"
  - "雇用保険事業所番号 (489)"
kumiaiSpec:
  - "支部コード"
  - "支部"
  - "分会コード"
  - "分会"
  - "班"
  - "組合員番号"
  - "氏名"
  - "氏名カナ"
  - "性別"
  - "生年月日"
  - "加入日"
  - "脱退日"
  - "職種コード" #new
  - "職種"
  - "階層コード" #new
  - "階層" #new
  - "就労先"
  - "就労先コード"
  - "台帳表示順"
  - "電話番号"
  - "携帯番号"
  - "FAX"
  - "郵便番号"
  - "住所"
  - "組合種別"
  - "共済区分"
  - "役職(本部)"
  - "役職(支部)"
  - "役職(分会)"
  - "役職(班)"
  - "被保険者番号"
  - "資格取得日"
  - "資格喪失日"
  - "国保階層名称"
officeSpec:
  - "事業所コード (1)"
  - "事業所名 (3)"
  - "事業主名 (5)"
  - "事業所郵便番号 (14)"
  - "都道府県名 (13)"
  - "事業所所在地1 (15)"
  - "事業所所在地2 (16)"
  - "事業所電話番号 (17)"
  - "FAX番号 (18)"
  - "事業開始年月日 (29)"
  - "事業廃止年月日 (30)"
  - "適用コード (142)"
  - "枝番 (143)"
  - "事務組合コード (144)"
  - "雇用保険番号 (152)"
  - "給与計算締切日 (47)"
  - "給与支払月 (48)"
  - "給与支払日 (49)"
  - "職安名_雇用保険 (271)"
officeSPSpec:
  - "事業所コード (1)"
  - "事業所名 (2)"
  - "事業所名カナ (3)"
  - "事業主名 (4)"
  - "事業主名カナ (5)"
  - "担当社労士コード (7)"
  - "社労士氏名 (8)"
  - "職安名 (26)"
  - "枝番 (65)"
  - "基幹番号 (69)"
  - "雇用委託年月日 (77)"
  - "雇用解除年月日 (78)"
  - "業種コード (115)"
  - "業種詳細 (116)"
  - "事業の概要 (117)"
  - "適用コード (64)"
  - "給与計算締切日 (47)"
  - "給与支払月 (48)"
  - "給与支払日 (49)"
  - "雇用保険番号 (72)"
  - "事業所郵便番号 (12)" #new
  - "事業所所在地1 (13)" #new
  - "事業所所在地2 (14)" #new
  - "事業所電話番号 (16)" #new
  - "FAX番号 (17)" #new
  - "労災成立年月日 (73)" #new
  - "労災委託年月日 (74)" #new
  - "労災解除年月日 (75)" #new
  - "雇用成立年月日 (76)" #new
  - "雇用委託年月日 (77)" #new
  - "雇用解除年月日 (78)" #new
  - "申告済概算保険料 (124)" #new
kumiaiOfficeSpec:
  - "代表組合員_組合員番号"
  - "事業所コード"
  - "支部名"
  - "事業所名"
  - "事業所名カナ"
  - "代表組合員_分会コード"
  - "代表組合員_分会名"
  - "事業主名"
  - "事業主名カナ"
  - "郵便番号"
  - "電話番号"
hitoriSpec:
  - "事業所コード (1)"
  - "事業所名 (3)"
  - "事業所名カナ (4)"
  - "事業主名 (5)"
  - "事業主名カナ (6)"
  - "担当社労士コード (7)"
  - "社労士氏名 (8)"
  - "適用コード (65)"
  - "枝番 (66)"
  - "基幹番号 (69)"
  ###
  - "氏名01 (115)"
  - "承認済給付基礎日額01 (116)"
  - "承認日01 (121)"
  - "脱退日01 (122)"
  - "氏名カナ01 (127)"
  ### 14
  - "氏名02 (129)"
  - "承認済給付基礎日額02 (130)"
  - "承認日02 (135)"
  - "脱退日02 (136)"
  - "氏名カナ02 (141)"
  ### 14
  - "氏名03 (143)"
  - "承認済給付基礎日額03 (144)"
  - "承認日03 (149)"
  - "脱退日03 (150)"
  - "氏名カナ03 (155)"
  ### 28
  - "氏名04 (157)"
  - "承認済給付基礎日額04 (158)"
  - "承認日04 (163)"
  - "脱退日04 (164)"
  - "氏名カナ04 (169)"
  ### 42
  - "氏名05 (171)"
  - "承認済給付基礎日額05 (172)"
  - "承認日05 (177)"
  - "脱退日05 (178)"
  - "氏名カナ05 (183)"
  ### 56
  - "氏名06 (185)"
  - "承認済給付基礎日額06 (186)"
  - "承認日06 (191)"
  - "脱退日06 (192)"
  - "氏名カナ06 (197)"
  ### 70
  - "氏名07 (199)"
  - "承認済給付基礎日額07 (200)"
  - "承認日07 (205)"
  - "脱退日07 (206)"
  - "氏名カナ07 (211)"
  ### 84
  - "氏名08 (213)"
  - "承認済給付基礎日額08 (214)"
  - "承認日08 (219)"
  - "脱退日08 (220)"
  - "氏名カナ08 (225)"
  ### 98
  - "氏名09 (227)"
  - "承認済給付基礎日額09 (228)"
  - "承認日09 (233)"
  - "脱退日09 (234)"
  - "氏名カナ09 (239)"
  ### 112
  - "氏名10 (241)"
  - "承認済給付基礎日額10 (242)"
  - "承認日10 (247)"
  - "脱退日10 (248)"
  - "氏名カナ10 (253)"
directoryFile:
  "d:/送信案件一覧.csv"
kumiaiFile:
  "c:/社労務/組合員データ活用.csv"
officeFile:
  "c:/社労務/hiho.csv"
officeSPFile:
  "c:/社労務/hiho3.csv"
kumiaiOfficeFile:
  "c:/社労務/事業所情報(CSV).csv"
hihoFile:
  "c:/社労務/hiho2.csv"
hitoriFile:
  "c:/社労務/hitorinitigaku.csv"
hitori2File:
  "c:/社労務/hitorinitigaku2.csv"
kumiaiDB:
  "kumiai.db"
officeDB:
  "office.db"
officeSPDB:
  "officesp.db"
kumiaiOfficeDB:
  "kumiaiOffice.db"
hihoDB:
  "hiho.db"
hitoriDB:
  "hitori.db"
hitori2DB:
  "hitori2.db"
