name:                Match
version:             0.4.0.0
github:              "githubuser/Match"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2018 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Match#readme>

dependencies:
  - base >= 4.7 && < 5
  - mtl
  - containers
  - time
  - attoparsec
  - text
  - parsec
  - transformers
  - parallel
  - Util
  - safe-exceptions
  - doctest
  - data-default-class
  - conduit
  - conduit-extra
  - xml-conduit
  - req
  - aeson
  - bytestring
  - directory
  - stm-conduit
  - heredocs
  - extensible
  - lens
  - yaml
  - heterocephalus
  - blaze-markup
  # - template-haskell
  - monad-skeleton
  - vector

default-extensions:
  - DataKinds
  - OverloadedLabels
  - TypeApplications
  - TypeOperators
  - OverloadedStrings

library:
  source-dirs: src
  ghc-options:
    - -O3
  dependencies:
    - aeson
    # - yaml
    - sqlite-simple
    - attoparsec-csv
    - split
    - directory
    - bytestring
    - path
    - filepath

executables:
  Match-exe:
    main:                Main.hs
    source-dirs:
    - app
    ghc-options:
    - -O3
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Match
    - async
    - optparse-applicative
  Ukyo:
    main:                Main.hs
    source-dirs:
    - app/Ukyo
    ghc-options:
    - -O3
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Match
    - async
    - optparse-applicative
  CreateDirectory:
    main:                Main.hs
    source-dirs:
    - app/CreateDirectory
    ghc-options:
    - -O3
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Match
   
tests:
  # Match-test:
  #   main:                Spec.hs
  #   source-dirs:         test
  #   ghc-options:
  #   - -threaded
  #   - -rtsopts
  #   - -with-rtsopts=-N
  #   dependencies:
  #   - Match
  Match-doctest:
    main: test/doctests.hs
    ghc-options:
    - -O0
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - doctest
    - doctest-discover
    - Match
    - base
