# #のあとはプログラムに関係しません。

# 組合員基幹情報ファイル
dataCSVFileName: "app/組合員データ活用.csv"

# 「付き」を記録するCSVファイルの名前。
# 適宜変更してください。
relationalFileName: "app/Tsuki.csv"

# 「付き」を考慮した並び順に変更。
# 例えば、B・C・XがA付、DがB付、Y・ZがC付の場合、
# A---B---D
# |   |
# |   C---Y
# |   |   |
# |   |   Z
# |   X
# E
# A→B→D→C→Y→Z→X→Eという順番に並べる。
# 元の方がいい場合はFalseにしておいて下さい。
sortCR: True

# 地図を作成します(インターネットに接続している環境が前提)。
# 【地図作成の仕組み】
# 住所を緯度・経度に変換するサービス(https://www.geocoding.jp/api)があります。
# このサービスにリクエストを送信し(住所のみ。氏名など他の情報は送信しません。)、
# 返ってきた緯度・経度の情報をデータベース(geocoder.db)に保存。データベースに保
# 存できた住所の緯度・経度は、データベースから読み出し、前回取得に失敗した住所は、
# 再度変換を試みます。
#         ↓
# データベースから読み出すなどして取得した緯度・経度は、クライエント側(支部のパ
# ソコンなど)で氏名・分会他の情報と結びつけ、地図上に投影します。
#         ↓
# Internet ExplorerなどのWebブラウザで、フォルダー内のindex.html上を開いてくださ
# い。このとき、地図を正しく表示するために、JavascriptをOnにしてください。

# ただし、上記サービスの利用規約上、5秒に1件以上のリクエストを送信できない(現在
# のプログラムでは10秒に1件送信)ので、新加入者や転入者が多数いるなど、データベー
# ス上に保存されていない住所が多数存在する状況では、地図作成に一定の時間がかかっ
# てしまいます。

# 下記の設定値doFetchがTrueの場合、データベースに保存されていない住所については、
# サービスにリクエストを送信して(再)変換を試みます。
# Falseの場合、データベースに保存されている住所のみで、地図を作成します。

# 作成の仕方は以下の通りです。
#
# (例)西院分会1班の地図を作成する(送信あり)場合。
# makeMapCR:
#   mapExecute: True
#   doFetch: True
#   mapBunkai: 1
#   mapHan: 1
#
# (例) 京北分会12班の地図を作成する(送信なし)場合。
# makeMapCR:
#   mapExecute: True
#   doFetch: False
#   mapBunkai: 21
#   mapHan: 12
#
# (例) 西院分会の地図を作成する(送信あり)場合。
# makeMapCR:
#   mapExecute: True
#   doFetch: True
#   mapBunkai: 1
#
# (例) 支部全体の地図を作成する(送信なし)場合。
# makeMapCR:
#   mapExecute: True
#   doFetch: False
#
makeMapCR:
  mapExecute: True
  doFetch: False
  mapBunkai: 21
  # mapHan: 1

# 「京都府京都市伏見区醍醐上ノ山町〜」などと
# 表記されても長ったらしいだけなので、「京都府」「京都市」「伏見区」は
# 全て組合員住所から削除します。
# また、同様に例えば「右京区」を組合員住所から削除したい場合は、
# 下行の「伏見区」の部分を「右京区」に変更してください。

# 不要な場合、下の行のコメントを外し、さらにその下の行の行頭に
# #をつけてください。
# addressRemove : []
addressRemove: ["京都府", "京都市", "右京区", "　"]

# 「職種」略称のリスト。右側は自由に変えてもらってもかまいません。
workReplaceAlist:
  - ["大工", "大工"]
  - ["左官", "左官"]
  - ["塗装工", "塗装"]
  - ["電工", "電工"]
  - ["板金工", "板金"]
  - ["給排水配管工", "給排水"]
  - ["空気調和配管工", "空調"]
  - ["タイル工", "タイル"]
  - ["建具工", "建具"]
  - ["造園工", "造園"]
  - ["土工", "土工"]
  - ["石工", "石工"]
  - ["鉄筋工", "鉄筋"]
  - ["鉄工", "鉄工"]
  - ["型枠大工", "型枠"]
  - ["表具工", "表具"]
  - ["ブロック工", "ブロック"]
  - ["ラス工", ""]
  - ["木舞・木型工", ""]
  - ["防水工", "防水"]
  - ["吹き付工", "吹付"]
  - ["畳工", "畳"]
  - ["ガラス工", "ガラス"]
  - ["サッシ工", "サッシ"]
  - ["瓦工", "瓦"]
  - ["屋根葺工", "屋根"]
  - ["ハツリ工", "ハツリ"]
  - ["家具工", "家具"]
  - ["溶接工", "溶接"]
  - ["解体工", "解体"]
  - ["建築金物業目立て", "金物"]
  - ["電信電話工事", "電話"]
  - ["手伝", "手伝 "]
  - ["鳶", "とび"]
  - ["木工", "木工"]
  - ["製材", "製材"]
  - ["内装仕上げ工", "内装"]
  - ["建材", "建材"]
  - ["設計", "設計"]
  - ["建築請負業", "請負"]
  - ["その他", "その他"]
  - ["クロス工", "クロス"]
  - ["スレート工", "スレート"]
  - ["看板工", "看板"]
  - ["機械設置・組立", "機械設置・組立"]
  - ["壁下地工", "壁下地"]
  - ["ＡＬＣ工", "ＡＬＣ"]
  - ["建築外装工", "サイディング"]
  - ["軽量天井工", "軽天"]
  - ["コンクリート工", "コンクリート"]
  - ["道路カッター", "カッター"]
  - ["保温工", "保温"]
  - ["美装・あく洗い", "美装"]
  - ["さく井工", "さく井"]
  - ["エクステリア工", "エクステリア"]
  - ["重機オペレータ", "重機オペ"]
  - ["杭打ち工", "杭打ち"]
  - ["材木業", "材木"]
  - ["テント工", "テント"]
  - ["ヘーベル工", "ヘーベル"]
  - ["浴槽工事業", "ユニットバス"]
  - ["現場監督", "監督"]
  - ["断熱工", "断熱"]
  - ["冷機", "冷機"]
  - ["ハウス組立て", "ハウス組立"]
  - ["クレーン", "クレーン"]
  - ["ボイラー", "ボイラー"]
  - ["測量技師", "測量"]
  - ["ガス設備・工事", "ガス"]
  - ["衛生設備・防虫", "防虫"]
  - ["工務店等一般事務職", "事務"]
  - ["厨房設備", "キッチン"]
  - ["ステンレス工", "ステンレス"]
  - ["床仕上げ工", "床仕上"]
  - ["プレハブ工", "プレハブ"]
  - ["シャッター工", "シャッター"]
  - ["建設機械運転手", "機械運転"]
  - ["圧接工", "圧接"]
  - ["宅建業", "宅建"]
  - ["営繕", "営繕"]
  - ["防音工・間仕切", "防音"]
  - ["道路工", "道路"]
  - ["舗装", "舗装"]
  - ["ボーリング工", "ボーリング"]
  - ["屋根板葺工", "屋根"]
  - ["住宅設備工", "住宅設備"]
  - ["土木", "土木"]
  - ["築炉工", "築炉"]
  - ["鉄骨工", "鉄骨"]
  - ["ドア取付け工", "ドア"]
  - ["とび・土工", "鳶土工"]
  - ["フェンス工", "フェンス"]
  - ["資材運搬運転手", "資材運搬"]
  - ["書記局", "書記"]

# 実際の出力部分。
# 職種を前のほうに出したい、など順番の変更は
# プログラム中の行を入れ替えればできます。
# また、不要のデータがある場合、行頭に「#」を打てば出力されません。
printOrder:
  - KNumber                     # 組合員番号
  - KName                       # 氏名
  - Bunkai                      # 分会名
  - Han                         # 班
  - KKind                       # 種別
  - KKyousai                    # 共済区分
  - BunkaichoMark               # 分会長マーク
  - BunkaiKaikeiMark            # 分会会計マーク
  - HanchoMark                  # 班長マーク
  - KAddress                    # 住所
  - KPhone                      # 電話番号
  - KCellPhone                  # 携帯電話
  - HowOld                      # 年齢
  - KWork                       # 職種
  - Explanation                 # 備考(e.g. "未・◯◯付")
  - KOffice                     # 就労先
  - KBunkaiY                    # 分会役職
  - KHanY                       # 班役職

# 他にも下記のようなものが指定できます。
  # - KKana                       # 氏名フリガナ
  # - HowOld                      # 年齢
  # - Shibu                       # 支部名
  # - ShibuCode                   # 支部コード
  # - BunkaiCode                  # 分会コード
  # - KSex                        # 性別
  # - KGot                        # 組合加入日
  # - KLost                       # 組合脱退日
  # - KBirthday                   # 生年月日
  # - KPostal                     # 郵便番号
  # - KFax                        # FAX
  # - KHonbuY                     # 本部役職
  # - KShibuY                     # 支部役職
  # - KBunkaiY                    # 分会役職
  # - KHanY                       # 班役職
  # - KKokuhoGet                  # 国保加入日
  # - KKokuhoLost                 # 国保脱退日
  # - KPrintOrder                 # 表示順
