topURLhost:
  "www.geocoding.jp"
topURLrest:
  "api"
dbname:
  "geocoder.db"
testcsv:
  "組合員データ活用.csv"
spec:
- "支部コード"
- "支部"
- "分会コード"
- "分会"
- "班"
- "組合員番号"
- "氏名"
- "氏名カナ"
- "性別"
- "生年月日"
- "加入日"
- "脱退日"
- "職種"
- "就労先"
- "就労先コード"
- "台帳表示順"
- "電話番号"
- "携帯番号"
- "FAX"
- "郵便番号"
- "住所"
- "組合種別"
- "共済区分"
- "役職(本部)"
- "役職(支部)"
- "役職(分会)"
- "役職(班)"
- "資格取得日"
- "資格喪失日"
jsfile:
  "src/index.js"
waitSeconds:
  10
