resolver: lts-9.21

packages:
- "../Util/"
- '.'

extra-deps: []

flags: {}

extra-include-dirs:
- d:\home\temp\Haskell\Snews\icu\include
- d:\home\temp\Haskell\Snews\icu\include\unicode
- d:\home\temp\Haskell\Snews\icu\bin
- C:\Users\Jumpei\Haskell\Snews\icu\include
- C:\Users\Jumpei\Haskell\Snews\icu\include\unicode
- C:\Users\Jumpei\Haskell\Snews\icu\bin
extra-lib-dirs:
- d:\home\temp\Haskell\Snews\icu\lib
- d:\home\temp\Haskell\Snews\icu\bin
- C:\Users\Jumpei\Haskell\Snews\icu\lib
- C:\Users\Jumpei\Haskell\Snews\icu\bin

# build:
#   library-profiling: true
#   executable-profiling: true
