resolver: lts-6.17

packages:
- "../Util/"
- '.'

extra-deps:
- extensible-0.4.10.1@sha256:4c8678a3a69b619b38143129027610954d0f7c58d305e5547eb5f3cbfa0a9513
- prettyprinter-1.2.1@sha256:69856d061c602917d578190265edb62b14f63a2e02bcc565adf31146f903a45b

flags: {}

extra-include-dirs: ["C:\\Users\\Jumpei\\Haskell\\Snews", "C:\\Users\\Jumpei\\Haskell\\icu\\include"]
extra-lib-dirs: ["C:\\Users\\Jumpei\\Haskell\\Snews", "C:\\Users\\Jumpei\\Haskell\\icu\\lib"]

build:
  library-profiling: true
  executable-profiling: true
