resolver: lts-6.17

packages:
- "../Util/"
- '.'

extra-deps: []

flags: {}

extra-include-dirs: ["C:\\Users\\Jumpei\\Haskell\\Snews", "C:\\Users\\Jumpei\\Haskell\\icu\\include"]
extra-lib-dirs: ["C:\\Users\\Jumpei\\Haskell\\Snews", "C:\\Users\\Jumpei\\Haskell\\icu\\lib"]

build:
  library-profiling: true
  executable-profiling: true
