resolver: lts-6.10

packages:
- "../Util/"
- '.'

extra-deps: []

# Override default flag values for local packages and extra-deps
flags: {}

# Extra package databases containing global packages

extra-include-dirs: ["f:\\Haskell", "f:\\Haskell\\icu\\include\\unicode", "f:\\Haskell\\icu\\include\\layout"]
extra-lib-dirs: ["f:\\Haskell", "f:\\Haskell\\icu\\lib"]
