resolver: lts-9.21

packages:
- "../Util/"
- '.'

extra-deps: []

flags: {}

extra-include-dirs: ["d:\\home\\temp\\Haskell\\Snews\\icu\\include", "d:\\home\\temp\\Haskell\\Snews\\icu\\include\\unicode", "d:\\home\\temp\\Haskell\\Snews\\icu\\bin"]
extra-lib-dirs: ["d:\\home\\temp\\Haskell\\Snews\\icu\\lib", "d:\\home\\temp\\Haskell\\Snews\\icu\\bin"]
# extra-include-dirs: ["d:\\home\\temp\\Haskell\\Snews", "d:\\home\\temp\\Haskell\\icu\\include", "d:\\home\\temp\\Haskell\\icu\\include\\unicode"]
# extra-lib-dirs: ["d:\\home\\temp\\Haskell\\Snews", "d:\\home\\temp\\Haskell\\icu\\lib"]

# build:
#   library-profiling: true
#   executable-profiling: true
