resolver: lts-6.17

packages:
- "../Util/"
- '.'

extra-deps: []

flags: {}

extra-include-dirs: ["f:\\Haskell\\Snews", "f:\\Haskell\\icu\\include"]
extra-lib-dirs: ["f:\\Haskell\\Snews", "f:\\Haskell\\icu\\lib"]
